<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <p>
      New Inbox From : {{$request->contact_email}}
    </p>

    <table>
      <tr>
        <th>
          <label>
            Name
          </label>
        </th>
        <td>
          <label>
            {{$request->contact_name}}
          </label>
        </td>
      </tr>
      <tr>
        <th>
          <label>
            Email
          </label>
        </th>
        <td>
          <label>
            {{$request->contact_email}}
          </label>
        </td>
      </tr>
      <tr>
        <th>
          <label>
            Subject
          </label>
        </th>
        <td>
          <label>
            {{$request->contact_subject}}
          </label>
        </td>
      </tr>
      <tr>
        <th>
          <label>
            Message
          </label>
        </th>
        <td>
          <label>
            {{$request->contact_message}}
          </label>
        </td>
      </tr>
    </table>

  </body>
</html>
